modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lightbind"
version = "${version}"
displayName = "LightBind"
authors = "Kall"
description = '''
'''
#logoFile = ""