modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lightbind"
version = "${version}"
displayName = "LightBind"
authors = "Kall"
description = '''
A Minecraft mod
'''
#logoFile = ""

[[mixins]]
config = "lightbind.mixins.json"
